from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Literal, Optional


AgentDepth = Literal["minimal", "balanced", "full"]
AgentRunMode = Literal["required", "optional", "skipped"]


@dataclass
class AgentTask:
    """
    A task assigned by ManagerAgent to a domain agent.
    """

    agent_key: str
    issue_type: str
    run_mode: AgentRunMode
    is_primary: bool = False
    task_description: str = ""
    reason: str = ""
    expected_output: List[str] = field(default_factory=list)


@dataclass
class AgentDecision:
    """
    Decision for whether a domain agent should run.
    """

    agent_key: str
    issue_type: str
    decision: AgentRunMode
    reason: str
    confidence: float = 0.5


@dataclass
class ExecutionPlan:
    """
    Execution plan generated by ManagerAgent.

    V3 Orchestrator executes agents according to this plan.
    """

    primary_issue_type: str
    secondary_issue_types: List[str]
    all_detected_issue_types: List[str]
    agent_depth: AgentDepth
    required_tasks: List[AgentTask] = field(default_factory=list)
    optional_tasks: List[AgentTask] = field(default_factory=list)
    skipped_tasks: List[AgentTask] = field(default_factory=list)
    decisions: List[AgentDecision] = field(default_factory=list)
    report_focus: str = ""
    budget_note: str = ""

    def executed_tasks(self, include_optional: bool = True) -> List[AgentTask]:
        if include_optional:
            return self.required_tasks + self.optional_tasks
        return self.required_tasks

    def to_markdown(self) -> str:
        lines = [
            "[EXECUTION_PLAN]",
            f"primary_issue_type: {self.primary_issue_type}",
            f"secondary_issue_types: {self.secondary_issue_types}",
            f"all_detected_issue_types: {self.all_detected_issue_types}",
            f"agent_depth: {self.agent_depth}",
            f"report_focus: {self.report_focus}",
            f"budget_note: {self.budget_note}",
            "",
            "[REQUIRED_AGENTS]",
        ]

        for task in self.required_tasks:
            lines.append(
                f"- {task.agent_key} | issue_type={task.issue_type} | "
                f"is_primary={task.is_primary} | reason={task.reason}"
            )

        lines.append("")
        lines.append("[OPTIONAL_AGENTS]")
        for task in self.optional_tasks:
            lines.append(
                f"- {task.agent_key} | issue_type={task.issue_type} | "
                f"is_primary={task.is_primary} | reason={task.reason}"
            )

        lines.append("")
        lines.append("[SKIPPED_AGENTS]")
        for task in self.skipped_tasks:
            lines.append(
                f"- {task.agent_key} | issue_type={task.issue_type} | "
                f"reason={task.reason}"
            )

        return "\n".join(lines)